#include "wvk_base_object.cpp"
#include "wvk_command_buffer.cpp"
//#include "wvk_extension.cpp"

#include "wvk_status.cpp"
#include "wvk_layer.cpp"
#include "wvk_dispatch_table.cpp"
#include "wvk_instance.cpp"
#include "wvk_physical_device.cpp"
#include "wvk_queue.cpp"
#include "wvk_dispatch_table.h"
#include "wvk_logical_device.cpp"
#include "wvk_command_pool.cpp"
#include "wvk_shader.cpp"

#include "MSWindows/wvk_dispatch_table_mswindows.cpp"

#include "Extensions/wvk_debug_utils_messenger.cpp"
#include "Extensions/wvk_surface.cpp"
#include "Extensions/MSWindows/wvk_khr_win32_surface_dispatch_table.cpp"
#include "Extensions/MSWindows/wvk_surface_mswindows.cpp"