# SPDX-License-Identifier: None
# Copyright (c) 2026 None

[workspace]
members = [
    # common
    "common",

    # samples: Not Engine
    "samples/not_engine/initialize",

    # samples: Wrapper Vulkan
    "samples/wvk/wvk_library_and_global_properties",

    # samples: Device Hardware Interface
    "samples/dhi/dhi_context",

    # SDK Vulkan
    "sdk_vulkan",

    # wrapper Vulkan
    "wrapper_vulkan",

    # 
    "device_hardware_interface",
]