# SPDX-License-Identifier: None
# Copyright (c) 2026 None

[workspace]
members = [
    # common
    "common",

    # samples: Not Engine
    "samples/not_engine/initialize",

    # samples Wrapper Vulkan:
    "samples/wvk/wvk_library",
    "samples/wvk/wvk_instance",
    "samples/wvk/wvk_physical_device",

    # samples: Device Hardware Interface
    "samples/dhi/dhi_context",

    # SDK Vulkan - SVK
    "sdk_vulkan",

    # Wrapper Vulkan - WVK
    "wrapper_vulkan",

    # Device Hardware Interface - DHI
    "device_hardware_interface",

    # utils
    "utils/tokenizer_xml",
    "utils/parser_svk",
    "utils/generator_svk",
]
