# SPDX-License-Identifier: None
# Copyright (c) 2026 None

[package]
name = "utils__tokenizer_xml"
version = "0.0.0"
edition = "2021"

[lib]
name = "utils__tokenizer_xml"
path = "_mods.rs"

[[bin]]
name = "utils__tokenizer_xml__benchmark"
path = "main.rs"

[dependencies]