// SPDX-License-Identifier: None
// Copyright (c) 2026 None

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// зависимости
// dependencies
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

use std::mem::MaybeUninit;

macro_rules! maybe_init {
    ($type: ty, $sType: expr) => {{
        let mut v = MaybeUninit::<$type>::uninit();

        unsafe {
            (*v.as_mut_ptr()).sType = $sType
        };

        v
    }}
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
///
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pub struct WvkPhysicalDeviceXProperties2 {
    pub vk_physical_device_push_constant_bank_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDevicePushConstantBankPropertiesNV>>,
    pub vk_physical_device_device_generated_commands_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV>>,
    pub vk_physical_device_cluster_acceleration_structure_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceClusterAccelerationStructurePropertiesNV>>,
    pub vk_physical_device_multi_draw_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceMultiDrawPropertiesEXT>>,
    pub vk_physical_device_push_descriptor_properties: Option<MaybeUninit<svk::VkPhysicalDevicePushDescriptorProperties>>,
    pub vk_physical_device_driver_properties: Option<MaybeUninit<svk::VkPhysicalDeviceDriverProperties>>,
    pub vk_physical_device_i_d_properties: Option<MaybeUninit<svk::VkPhysicalDeviceIDProperties>>,
    pub vk_physical_device_multiview_properties: Option<MaybeUninit<svk::VkPhysicalDeviceMultiviewProperties>>,
    pub vk_physical_device_discard_rectangle_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceDiscardRectanglePropertiesEXT>>,
    pub vk_physical_device_multiview_per_view_attributes_properties_n_v_x: Option<MaybeUninit<svk::VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX>>,
    pub vk_physical_device_subgroup_properties: Option<MaybeUninit<svk::VkPhysicalDeviceSubgroupProperties>>,
    pub vk_physical_device_point_clipping_properties: Option<MaybeUninit<svk::VkPhysicalDevicePointClippingProperties>>,
    pub vk_physical_device_protected_memory_properties: Option<MaybeUninit<svk::VkPhysicalDeviceProtectedMemoryProperties>>,
    pub vk_physical_device_sampler_filter_minmax_properties: Option<MaybeUninit<svk::VkPhysicalDeviceSamplerFilterMinmaxProperties>>,
    pub vk_physical_device_sample_locations_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceSampleLocationsPropertiesEXT>>,
    pub vk_physical_device_blend_operation_advanced_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT>>,
    pub vk_physical_device_inline_uniform_block_properties: Option<MaybeUninit<svk::VkPhysicalDeviceInlineUniformBlockProperties>>,
    pub vk_physical_device_maintenance_3_properties: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance3Properties>>,
    pub vk_physical_device_maintenance_4_properties: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance4Properties>>,
    pub vk_physical_device_maintenance_5_properties: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance5Properties>>,
    pub vk_physical_device_maintenance_6_properties: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance6Properties>>,
    pub vk_physical_device_maintenance_7_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance7PropertiesKHR>>,
    pub vk_physical_device_layered_api_properties_list_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceLayeredApiPropertiesListKHR>>,
    pub vk_physical_device_maintenance_9_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance9PropertiesKHR>>,
    pub vk_physical_device_maintenance_1_0_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceMaintenance10PropertiesKHR>>,
    pub vk_physical_device_float_controls_properties: Option<MaybeUninit<svk::VkPhysicalDeviceFloatControlsProperties>>,
    pub vk_physical_device_presentation_properties_a_n_d_r_o_i_d: Option<MaybeUninit<svk::VkPhysicalDevicePresentationPropertiesANDROID>>,
    pub vk_physical_device_external_memory_host_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceExternalMemoryHostPropertiesEXT>>,
    pub vk_physical_device_conservative_rasterization_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceConservativeRasterizationPropertiesEXT>>,
    pub vk_physical_device_shader_core_properties_a_m_d: Option<MaybeUninit<svk::VkPhysicalDeviceShaderCorePropertiesAMD>>,
    pub vk_physical_device_shader_core_properties_2_a_m_d: Option<MaybeUninit<svk::VkPhysicalDeviceShaderCoreProperties2AMD>>,
    pub vk_physical_device_descriptor_indexing_properties: Option<MaybeUninit<svk::VkPhysicalDeviceDescriptorIndexingProperties>>,
    pub vk_physical_device_timeline_semaphore_properties: Option<MaybeUninit<svk::VkPhysicalDeviceTimelineSemaphoreProperties>>,
    pub vk_physical_device_vertex_attribute_divisor_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT>>,
    pub vk_physical_device_vertex_attribute_divisor_properties: Option<MaybeUninit<svk::VkPhysicalDeviceVertexAttributeDivisorProperties>>,
    pub vk_physical_device_p_c_i_bus_info_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDevicePCIBusInfoPropertiesEXT>>,
    pub vk_physical_device_depth_stencil_resolve_properties: Option<MaybeUninit<svk::VkPhysicalDeviceDepthStencilResolveProperties>>,
    pub vk_physical_device_transform_feedback_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceTransformFeedbackPropertiesEXT>>,
    pub vk_physical_device_compute_shader_derivatives_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceComputeShaderDerivativesPropertiesKHR>>,
    pub vk_physical_device_copy_memory_indirect_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceCopyMemoryIndirectPropertiesKHR>>,
    pub vk_physical_device_memory_decompression_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceMemoryDecompressionPropertiesEXT>>,
    pub vk_physical_device_shading_rate_image_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceShadingRateImagePropertiesNV>>,
    pub vk_physical_device_mesh_shader_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceMeshShaderPropertiesNV>>,
    pub vk_physical_device_mesh_shader_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceMeshShaderPropertiesEXT>>,
    pub vk_physical_device_acceleration_structure_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceAccelerationStructurePropertiesKHR>>,
    pub vk_physical_device_ray_tracing_pipeline_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceRayTracingPipelinePropertiesKHR>>,
    pub vk_physical_device_ray_tracing_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceRayTracingPropertiesNV>>,
    pub vk_physical_device_fragment_density_map_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentDensityMapPropertiesEXT>>,
    pub vk_physical_device_fragment_density_map_2_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentDensityMap2PropertiesEXT>>,
    pub vk_physical_device_fragment_density_map_offset_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT>>,
    pub vk_physical_device_cooperative_matrix_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceCooperativeMatrixPropertiesNV>>,
    pub vk_physical_device_performance_query_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDevicePerformanceQueryPropertiesKHR>>,
    pub vk_physical_device_shader_s_m_builtins_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceShaderSMBuiltinsPropertiesNV>>,
    pub vk_physical_device_texel_buffer_alignment_properties: Option<MaybeUninit<svk::VkPhysicalDeviceTexelBufferAlignmentProperties>>,
    pub vk_physical_device_subgroup_size_control_properties: Option<MaybeUninit<svk::VkPhysicalDeviceSubgroupSizeControlProperties>>,
    pub vk_physical_device_subpass_shading_properties_h_u_a_w_e_i: Option<MaybeUninit<svk::VkPhysicalDeviceSubpassShadingPropertiesHUAWEI>>,
    pub vk_physical_device_cluster_culling_shader_properties_h_u_a_w_e_i: Option<MaybeUninit<svk::VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI>>,
    pub vk_physical_device_line_rasterization_properties: Option<MaybeUninit<svk::VkPhysicalDeviceLineRasterizationProperties>>,
    pub vk_physical_device_vulkan_1_1_properties: Option<MaybeUninit<svk::VkPhysicalDeviceVulkan11Properties>>,
    pub vk_physical_device_vulkan_1_2_properties: Option<MaybeUninit<svk::VkPhysicalDeviceVulkan12Properties>>,
    pub vk_physical_device_vulkan_1_3_properties: Option<MaybeUninit<svk::VkPhysicalDeviceVulkan13Properties>>,
    pub vk_physical_device_vulkan_1_4_properties: Option<MaybeUninit<svk::VkPhysicalDeviceVulkan14Properties>>,
    pub vk_physical_device_gpa_properties_a_m_d: Option<MaybeUninit<svk::VkPhysicalDeviceGpaPropertiesAMD>>,
    pub vk_physical_device_gpa_properties_2_a_m_d: Option<MaybeUninit<svk::VkPhysicalDeviceGpaProperties2AMD>>,
    pub vk_physical_device_custom_border_color_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceCustomBorderColorPropertiesEXT>>,
    pub vk_physical_device_extended_dynamic_state_3_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceExtendedDynamicState3PropertiesEXT>>,
    pub vk_physical_device_partitioned_acceleration_structure_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDevicePartitionedAccelerationStructurePropertiesNV>>,
    pub vk_physical_device_robustness_2_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceRobustness2PropertiesKHR>>,
    pub vk_physical_device_portability_subset_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDevicePortabilitySubsetPropertiesKHR>>,
    pub vk_physical_device_fragment_shading_rate_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentShadingRatePropertiesKHR>>,
    pub vk_physical_device_fragment_shading_rate_enums_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentShadingRateEnumsPropertiesNV>>,
    pub vk_physical_device_legacy_vertex_attributes_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceLegacyVertexAttributesPropertiesEXT>>,
    pub vk_physical_device_device_generated_commands_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT>>,
    pub vk_physical_device_host_image_copy_properties: Option<MaybeUninit<svk::VkPhysicalDeviceHostImageCopyProperties>>,
    pub vk_physical_device_vulkan_s_c_1_0_properties: Option<MaybeUninit<svk::VkPhysicalDeviceVulkanSC10Properties>>,
    pub vk_physical_device_provoking_vertex_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceProvokingVertexPropertiesEXT>>,
    pub vk_physical_device_descriptor_buffer_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceDescriptorBufferPropertiesEXT>>,
    pub vk_physical_device_descriptor_buffer_density_map_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT>>,
    pub vk_physical_device_shader_integer_dot_product_properties: Option<MaybeUninit<svk::VkPhysicalDeviceShaderIntegerDotProductProperties>>,
    pub vk_physical_device_drm_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceDrmPropertiesEXT>>,
    pub vk_physical_device_fragment_shader_barycentric_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentShaderBarycentricPropertiesKHR>>,
    pub vk_physical_device_pipeline_binary_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDevicePipelineBinaryPropertiesKHR>>,
    pub vk_physical_device_graphics_pipeline_library_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT>>,
    pub vk_physical_device_nested_command_buffer_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceNestedCommandBufferPropertiesEXT>>,
    pub vk_physical_device_shader_module_identifier_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceShaderModuleIdentifierPropertiesEXT>>,
    pub vk_physical_device_opacity_micromap_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceOpacityMicromapPropertiesKHR>>,
    pub vk_physical_device_opacity_micromap_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceOpacityMicromapPropertiesEXT>>,
    pub vk_physical_device_displacement_micromap_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceDisplacementMicromapPropertiesNV>>,
    pub vk_physical_device_pipeline_robustness_properties: Option<MaybeUninit<svk::VkPhysicalDevicePipelineRobustnessProperties>>,
    pub vk_physical_device_shader_multiple_wait_queues_properties_q_c_o_m: Option<MaybeUninit<svk::VkPhysicalDeviceShaderMultipleWaitQueuesPropertiesQCOM>>,
    pub vk_physical_device_image_processing_properties_q_c_o_m: Option<MaybeUninit<svk::VkPhysicalDeviceImageProcessingPropertiesQCOM>>,
    pub vk_physical_device_optical_flow_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceOpticalFlowPropertiesNV>>,
    pub vk_physical_device_fault_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceFaultPropertiesKHR>>,
    pub vk_physical_device_shader_core_builtins_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM>>,
    pub vk_physical_device_ray_tracing_invocation_reorder_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceRayTracingInvocationReorderPropertiesEXT>>,
    pub vk_physical_device_ray_tracing_invocation_reorder_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceRayTracingInvocationReorderPropertiesNV>>,
    pub vk_physical_device_extended_sparse_address_space_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceExtendedSparseAddressSpacePropertiesNV>>,
    pub vk_physical_device_shader_core_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceShaderCorePropertiesARM>>,
    pub vk_physical_device_shader_object_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceShaderObjectPropertiesEXT>>,
    pub vk_physical_device_shader_tile_image_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceShaderTileImagePropertiesEXT>>,
    pub vk_physical_device_cooperative_matrix_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceCooperativeMatrixPropertiesKHR>>,
    pub vk_physical_device_shader_enqueue_properties_a_m_d_x: Option<MaybeUninit<svk::VkPhysicalDeviceShaderEnqueuePropertiesAMDX>>,
    pub vk_physical_device_tile_memory_heap_properties_q_c_o_m: Option<MaybeUninit<svk::VkPhysicalDeviceTileMemoryHeapPropertiesQCOM>>,
    pub vk_physical_device_image_processing_2_properties_q_c_o_m: Option<MaybeUninit<svk::VkPhysicalDeviceImageProcessing2PropertiesQCOM>>,
    pub vk_physical_device_layered_driver_properties_m_s_f_t: Option<MaybeUninit<svk::VkPhysicalDeviceLayeredDriverPropertiesMSFT>>,
    pub vk_physical_device_external_format_resolve_properties_a_n_d_r_o_i_d: Option<MaybeUninit<svk::VkPhysicalDeviceExternalFormatResolvePropertiesANDROID>>,
    pub vk_physical_device_cuda_kernel_launch_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceCudaKernelLaunchPropertiesNV>>,
    pub vk_physical_device_scheduling_controls_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceSchedulingControlsPropertiesARM>>,
    pub vk_physical_device_scheduling_controls_dispatch_parameters_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceSchedulingControlsDispatchParametersPropertiesARM>>,
    pub vk_physical_device_render_pass_striped_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceRenderPassStripedPropertiesARM>>,
    pub vk_physical_device_map_memory_placed_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceMapMemoryPlacedPropertiesEXT>>,
    pub vk_physical_device_image_alignment_control_properties_m_e_s_a: Option<MaybeUninit<svk::VkPhysicalDeviceImageAlignmentControlPropertiesMESA>>,
    pub vk_physical_device_cooperative_matrix_2_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceCooperativeMatrix2PropertiesNV>>,
    pub vk_physical_device_cooperative_vector_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceCooperativeVectorPropertiesNV>>,
    pub vk_physical_device_tile_shading_properties_q_c_o_m: Option<MaybeUninit<svk::VkPhysicalDeviceTileShadingPropertiesQCOM>>,
    pub vk_physical_device_fragment_density_map_layered_properties_v_a_l_v_e: Option<MaybeUninit<svk::VkPhysicalDeviceFragmentDensityMapLayeredPropertiesVALVE>>,
    pub vk_physical_device_external_compute_queue_properties_n_v: Option<MaybeUninit<svk::VkPhysicalDeviceExternalComputeQueuePropertiesNV>>,
    pub vk_physical_device_tensor_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceTensorPropertiesARM>>,
    pub vk_physical_device_descriptor_buffer_tensor_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceDescriptorBufferTensorPropertiesARM>>,
    pub vk_physical_device_presentation_properties_o_h_o_s: Option<MaybeUninit<svk::VkPhysicalDevicePresentationPropertiesOHOS>>,
    pub vk_physical_device_queue_perf_hint_properties_q_c_o_m: Option<MaybeUninit<svk::VkPhysicalDeviceQueuePerfHintPropertiesQCOM>>,
    pub vk_physical_device_performance_counters_by_region_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDevicePerformanceCountersByRegionPropertiesARM>>,
    pub vk_physical_device_shader_long_vector_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceShaderLongVectorPropertiesEXT>>,
    pub vk_physical_device_shader_split_barrier_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceShaderSplitBarrierPropertiesEXT>>,
    pub vk_physical_device_descriptor_heap_properties_e_x_t: Option<MaybeUninit<svk::VkPhysicalDeviceDescriptorHeapPropertiesEXT>>,
    pub vk_physical_device_descriptor_heap_tensor_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceDescriptorHeapTensorPropertiesARM>>,
    pub vk_physical_device_shader_instrumentation_properties_a_r_m: Option<MaybeUninit<svk::VkPhysicalDeviceShaderInstrumentationPropertiesARM>>,
    pub vk_physical_device_shader_abort_properties_k_h_r: Option<MaybeUninit<svk::VkPhysicalDeviceShaderAbortPropertiesKHR>>,
    pub vk_physical_device_buffer_device_address_allocation_alignment_properties_v_a_l_v_e: Option<MaybeUninit<svk::VkPhysicalDeviceBufferDeviceAddressAllocationAlignmentPropertiesVALVE>>,

}

impl WvkPhysicalDeviceXProperties2 {
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ///
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    pub fn create() -> Self {
        Self {
            vk_physical_device_push_constant_bank_properties_n_v: Some(maybe_init!(svk::VkPhysicalDevicePushConstantBankPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PUSH_CONSTANT_BANK_PROPERTIES_NV)),
            vk_physical_device_device_generated_commands_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_PROPERTIES_NV)),
            vk_physical_device_cluster_acceleration_structure_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceClusterAccelerationStructurePropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_ACCELERATION_STRUCTURE_PROPERTIES_NV)),
            vk_physical_device_multi_draw_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceMultiDrawPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTI_DRAW_PROPERTIES_EXT)),
            vk_physical_device_push_descriptor_properties: Some(maybe_init!(svk::VkPhysicalDevicePushDescriptorProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES)),
            vk_physical_device_driver_properties: Some(maybe_init!(svk::VkPhysicalDeviceDriverProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES)),
            vk_physical_device_i_d_properties: Some(maybe_init!(svk::VkPhysicalDeviceIDProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES)),
            vk_physical_device_multiview_properties: Some(maybe_init!(svk::VkPhysicalDeviceMultiviewProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES)),
            vk_physical_device_discard_rectangle_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceDiscardRectanglePropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES_EXT)),
            vk_physical_device_multiview_per_view_attributes_properties_n_v_x: Some(maybe_init!(svk::VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX)),
            vk_physical_device_subgroup_properties: Some(maybe_init!(svk::VkPhysicalDeviceSubgroupProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES)),
            vk_physical_device_point_clipping_properties: Some(maybe_init!(svk::VkPhysicalDevicePointClippingProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES)),
            vk_physical_device_protected_memory_properties: Some(maybe_init!(svk::VkPhysicalDeviceProtectedMemoryProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES)),
            vk_physical_device_sampler_filter_minmax_properties: Some(maybe_init!(svk::VkPhysicalDeviceSamplerFilterMinmaxProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES)),
            vk_physical_device_sample_locations_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceSampleLocationsPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES_EXT)),
            vk_physical_device_blend_operation_advanced_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES_EXT)),
            vk_physical_device_inline_uniform_block_properties: Some(maybe_init!(svk::VkPhysicalDeviceInlineUniformBlockProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES)),
            vk_physical_device_maintenance_3_properties: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance3Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES)),
            vk_physical_device_maintenance_4_properties: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance4Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_PROPERTIES)),
            vk_physical_device_maintenance_5_properties: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance5Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES)),
            vk_physical_device_maintenance_6_properties: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance6Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_6_PROPERTIES)),
            vk_physical_device_maintenance_7_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance7PropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_7_PROPERTIES_KHR)),
            vk_physical_device_layered_api_properties_list_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceLayeredApiPropertiesListKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LAYERED_API_PROPERTIES_LIST_KHR)),
            vk_physical_device_maintenance_9_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance9PropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_9_PROPERTIES_KHR)),
            vk_physical_device_maintenance_1_0_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceMaintenance10PropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_10_PROPERTIES_KHR)),
            vk_physical_device_float_controls_properties: Some(maybe_init!(svk::VkPhysicalDeviceFloatControlsProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES)),
            vk_physical_device_presentation_properties_a_n_d_r_o_i_d: Some(maybe_init!(svk::VkPhysicalDevicePresentationPropertiesANDROID, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENTATION_PROPERTIES_ANDROID)),
            vk_physical_device_external_memory_host_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceExternalMemoryHostPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT)),
            vk_physical_device_conservative_rasterization_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceConservativeRasterizationPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT)),
            vk_physical_device_shader_core_properties_a_m_d: Some(maybe_init!(svk::VkPhysicalDeviceShaderCorePropertiesAMD, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD)),
            vk_physical_device_shader_core_properties_2_a_m_d: Some(maybe_init!(svk::VkPhysicalDeviceShaderCoreProperties2AMD, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_2_AMD)),
            vk_physical_device_descriptor_indexing_properties: Some(maybe_init!(svk::VkPhysicalDeviceDescriptorIndexingProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES)),
            vk_physical_device_timeline_semaphore_properties: Some(maybe_init!(svk::VkPhysicalDeviceTimelineSemaphoreProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_PROPERTIES)),
            vk_physical_device_vertex_attribute_divisor_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT)),
            vk_physical_device_vertex_attribute_divisor_properties: Some(maybe_init!(svk::VkPhysicalDeviceVertexAttributeDivisorProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES)),
            vk_physical_device_p_c_i_bus_info_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDevicePCIBusInfoPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PCI_BUS_INFO_PROPERTIES_EXT)),
            vk_physical_device_depth_stencil_resolve_properties: Some(maybe_init!(svk::VkPhysicalDeviceDepthStencilResolveProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES)),
            vk_physical_device_transform_feedback_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceTransformFeedbackPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_PROPERTIES_EXT)),
            vk_physical_device_compute_shader_derivatives_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceComputeShaderDerivativesPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_PROPERTIES_KHR)),
            vk_physical_device_copy_memory_indirect_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceCopyMemoryIndirectPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COPY_MEMORY_INDIRECT_PROPERTIES_KHR)),
            vk_physical_device_memory_decompression_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceMemoryDecompressionPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_DECOMPRESSION_PROPERTIES_EXT)),
            vk_physical_device_shading_rate_image_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceShadingRateImagePropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_PROPERTIES_NV)),
            vk_physical_device_mesh_shader_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceMeshShaderPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_NV)),
            vk_physical_device_mesh_shader_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceMeshShaderPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_EXT)),
            vk_physical_device_acceleration_structure_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceAccelerationStructurePropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_PROPERTIES_KHR)),
            vk_physical_device_ray_tracing_pipeline_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceRayTracingPipelinePropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_PROPERTIES_KHR)),
            vk_physical_device_ray_tracing_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceRayTracingPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PROPERTIES_NV)),
            vk_physical_device_fragment_density_map_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceFragmentDensityMapPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_PROPERTIES_EXT)),
            vk_physical_device_fragment_density_map_2_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceFragmentDensityMap2PropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_2_PROPERTIES_EXT)),
            vk_physical_device_fragment_density_map_offset_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceFragmentDensityMapOffsetPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_PROPERTIES_EXT)),
            vk_physical_device_cooperative_matrix_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceCooperativeMatrixPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_NV)),
            vk_physical_device_performance_query_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDevicePerformanceQueryPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PERFORMANCE_QUERY_PROPERTIES_KHR)),
            vk_physical_device_shader_s_m_builtins_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceShaderSMBuiltinsPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SM_BUILTINS_PROPERTIES_NV)),
            vk_physical_device_texel_buffer_alignment_properties: Some(maybe_init!(svk::VkPhysicalDeviceTexelBufferAlignmentProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXEL_BUFFER_ALIGNMENT_PROPERTIES)),
            vk_physical_device_subgroup_size_control_properties: Some(maybe_init!(svk::VkPhysicalDeviceSubgroupSizeControlProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_PROPERTIES)),
            vk_physical_device_subpass_shading_properties_h_u_a_w_e_i: Some(maybe_init!(svk::VkPhysicalDeviceSubpassShadingPropertiesHUAWEI, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_SHADING_PROPERTIES_HUAWEI)),
            vk_physical_device_cluster_culling_shader_properties_h_u_a_w_e_i: Some(maybe_init!(svk::VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_PROPERTIES_HUAWEI)),
            vk_physical_device_line_rasterization_properties: Some(maybe_init!(svk::VkPhysicalDeviceLineRasterizationProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LINE_RASTERIZATION_PROPERTIES)),
            vk_physical_device_vulkan_1_1_properties: Some(maybe_init!(svk::VkPhysicalDeviceVulkan11Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES)),
            vk_physical_device_vulkan_1_2_properties: Some(maybe_init!(svk::VkPhysicalDeviceVulkan12Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES)),
            vk_physical_device_vulkan_1_3_properties: Some(maybe_init!(svk::VkPhysicalDeviceVulkan13Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES)),
            vk_physical_device_vulkan_1_4_properties: Some(maybe_init!(svk::VkPhysicalDeviceVulkan14Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_4_PROPERTIES)),
            vk_physical_device_gpa_properties_a_m_d: Some(maybe_init!(svk::VkPhysicalDeviceGpaPropertiesAMD, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GPA_PROPERTIES_AMD)),
            vk_physical_device_gpa_properties_2_a_m_d: Some(maybe_init!(svk::VkPhysicalDeviceGpaProperties2AMD, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GPA_PROPERTIES_2_AMD)),
            vk_physical_device_custom_border_color_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceCustomBorderColorPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_BORDER_COLOR_PROPERTIES_EXT)),
            vk_physical_device_extended_dynamic_state_3_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceExtendedDynamicState3PropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_PROPERTIES_EXT)),
            vk_physical_device_partitioned_acceleration_structure_properties_n_v: Some(maybe_init!(svk::VkPhysicalDevicePartitionedAccelerationStructurePropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PARTITIONED_ACCELERATION_STRUCTURE_PROPERTIES_NV)),
            vk_physical_device_robustness_2_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceRobustness2PropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_KHR)),
            vk_physical_device_portability_subset_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDevicePortabilitySubsetPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PORTABILITY_SUBSET_PROPERTIES_KHR)),
            vk_physical_device_fragment_shading_rate_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceFragmentShadingRatePropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADING_RATE_PROPERTIES_KHR)),
            vk_physical_device_fragment_shading_rate_enums_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceFragmentShadingRateEnumsPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADING_RATE_ENUMS_PROPERTIES_NV)),
            vk_physical_device_legacy_vertex_attributes_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceLegacyVertexAttributesPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LEGACY_VERTEX_ATTRIBUTES_PROPERTIES_EXT)),
            vk_physical_device_device_generated_commands_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEVICE_GENERATED_COMMANDS_PROPERTIES_EXT)),
            vk_physical_device_host_image_copy_properties: Some(maybe_init!(svk::VkPhysicalDeviceHostImageCopyProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_IMAGE_COPY_PROPERTIES)),
            vk_physical_device_vulkan_s_c_1_0_properties: Some(maybe_init!(svk::VkPhysicalDeviceVulkanSC10Properties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_SC_1_0_PROPERTIES)),
            vk_physical_device_provoking_vertex_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceProvokingVertexPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROVOKING_VERTEX_PROPERTIES_EXT)),
            vk_physical_device_descriptor_buffer_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceDescriptorBufferPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_PROPERTIES_EXT)),
            vk_physical_device_descriptor_buffer_density_map_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_DENSITY_MAP_PROPERTIES_EXT)),
            vk_physical_device_shader_integer_dot_product_properties: Some(maybe_init!(svk::VkPhysicalDeviceShaderIntegerDotProductProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_PROPERTIES)),
            vk_physical_device_drm_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceDrmPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRM_PROPERTIES_EXT)),
            vk_physical_device_fragment_shader_barycentric_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceFragmentShaderBarycentricPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_PROPERTIES_KHR)),
            vk_physical_device_pipeline_binary_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDevicePipelineBinaryPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_BINARY_PROPERTIES_KHR)),
            vk_physical_device_graphics_pipeline_library_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_PROPERTIES_EXT)),
            vk_physical_device_nested_command_buffer_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceNestedCommandBufferPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_NESTED_COMMAND_BUFFER_PROPERTIES_EXT)),
            vk_physical_device_shader_module_identifier_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceShaderModuleIdentifierPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MODULE_IDENTIFIER_PROPERTIES_EXT)),
            vk_physical_device_opacity_micromap_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceOpacityMicromapPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_OPACITY_MICROMAP_PROPERTIES_KHR)),
            vk_physical_device_opacity_micromap_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceOpacityMicromapPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_OPACITY_MICROMAP_PROPERTIES_EXT)),
            vk_physical_device_displacement_micromap_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceDisplacementMicromapPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISPLACEMENT_MICROMAP_PROPERTIES_NV)),
            vk_physical_device_pipeline_robustness_properties: Some(maybe_init!(svk::VkPhysicalDevicePipelineRobustnessProperties, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_ROBUSTNESS_PROPERTIES)),
            vk_physical_device_shader_multiple_wait_queues_properties_q_c_o_m: Some(maybe_init!(svk::VkPhysicalDeviceShaderMultipleWaitQueuesPropertiesQCOM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MULTIPLE_WAIT_QUEUES_PROPERTIES_QCOM)),
            vk_physical_device_image_processing_properties_q_c_o_m: Some(maybe_init!(svk::VkPhysicalDeviceImageProcessingPropertiesQCOM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_PROPERTIES_QCOM)),
            vk_physical_device_optical_flow_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceOpticalFlowPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_OPTICAL_FLOW_PROPERTIES_NV)),
            vk_physical_device_fault_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceFaultPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FAULT_PROPERTIES_KHR)),
            vk_physical_device_shader_core_builtins_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_PROPERTIES_ARM)),
            vk_physical_device_ray_tracing_invocation_reorder_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceRayTracingInvocationReorderPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_PROPERTIES_EXT)),
            vk_physical_device_ray_tracing_invocation_reorder_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceRayTracingInvocationReorderPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_INVOCATION_REORDER_PROPERTIES_NV)),
            vk_physical_device_extended_sparse_address_space_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceExtendedSparseAddressSpacePropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_SPARSE_ADDRESS_SPACE_PROPERTIES_NV)),
            vk_physical_device_shader_core_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceShaderCorePropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_ARM)),
            vk_physical_device_shader_object_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceShaderObjectPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_OBJECT_PROPERTIES_EXT)),
            vk_physical_device_shader_tile_image_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceShaderTileImagePropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_TILE_IMAGE_PROPERTIES_EXT)),
            vk_physical_device_cooperative_matrix_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceCooperativeMatrixPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_KHR)),
            vk_physical_device_shader_enqueue_properties_a_m_d_x: Some(maybe_init!(svk::VkPhysicalDeviceShaderEnqueuePropertiesAMDX, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ENQUEUE_PROPERTIES_AMDX)),
            vk_physical_device_tile_memory_heap_properties_q_c_o_m: Some(maybe_init!(svk::VkPhysicalDeviceTileMemoryHeapPropertiesQCOM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_MEMORY_HEAP_PROPERTIES_QCOM)),
            vk_physical_device_image_processing_2_properties_q_c_o_m: Some(maybe_init!(svk::VkPhysicalDeviceImageProcessing2PropertiesQCOM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_2_PROPERTIES_QCOM)),
            vk_physical_device_layered_driver_properties_m_s_f_t: Some(maybe_init!(svk::VkPhysicalDeviceLayeredDriverPropertiesMSFT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LAYERED_DRIVER_PROPERTIES_MSFT)),
            vk_physical_device_external_format_resolve_properties_a_n_d_r_o_i_d: Some(maybe_init!(svk::VkPhysicalDeviceExternalFormatResolvePropertiesANDROID, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FORMAT_RESOLVE_PROPERTIES_ANDROID)),
            vk_physical_device_cuda_kernel_launch_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceCudaKernelLaunchPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUDA_KERNEL_LAUNCH_PROPERTIES_NV)),
            vk_physical_device_scheduling_controls_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceSchedulingControlsPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCHEDULING_CONTROLS_PROPERTIES_ARM)),
            vk_physical_device_scheduling_controls_dispatch_parameters_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceSchedulingControlsDispatchParametersPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCHEDULING_CONTROLS_DISPATCH_PARAMETERS_PROPERTIES_ARM)),
            vk_physical_device_render_pass_striped_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceRenderPassStripedPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RENDER_PASS_STRIPED_PROPERTIES_ARM)),
            vk_physical_device_map_memory_placed_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceMapMemoryPlacedPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAP_MEMORY_PLACED_PROPERTIES_EXT)),
            vk_physical_device_image_alignment_control_properties_m_e_s_a: Some(maybe_init!(svk::VkPhysicalDeviceImageAlignmentControlPropertiesMESA, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ALIGNMENT_CONTROL_PROPERTIES_MESA)),
            vk_physical_device_cooperative_matrix_2_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceCooperativeMatrix2PropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_2_PROPERTIES_NV)),
            vk_physical_device_cooperative_vector_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceCooperativeVectorPropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_VECTOR_PROPERTIES_NV)),
            vk_physical_device_tile_shading_properties_q_c_o_m: Some(maybe_init!(svk::VkPhysicalDeviceTileShadingPropertiesQCOM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_SHADING_PROPERTIES_QCOM)),
            vk_physical_device_fragment_density_map_layered_properties_v_a_l_v_e: Some(maybe_init!(svk::VkPhysicalDeviceFragmentDensityMapLayeredPropertiesVALVE, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_LAYERED_PROPERTIES_VALVE)),
            vk_physical_device_external_compute_queue_properties_n_v: Some(maybe_init!(svk::VkPhysicalDeviceExternalComputeQueuePropertiesNV, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_COMPUTE_QUEUE_PROPERTIES_NV)),
            vk_physical_device_tensor_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceTensorPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TENSOR_PROPERTIES_ARM)),
            vk_physical_device_descriptor_buffer_tensor_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceDescriptorBufferTensorPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_TENSOR_PROPERTIES_ARM)),
            vk_physical_device_presentation_properties_o_h_o_s: Some(maybe_init!(svk::VkPhysicalDevicePresentationPropertiesOHOS, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENTATION_PROPERTIES_OHOS)),
            vk_physical_device_queue_perf_hint_properties_q_c_o_m: Some(maybe_init!(svk::VkPhysicalDeviceQueuePerfHintPropertiesQCOM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_QUEUE_PERF_HINT_PROPERTIES_QCOM)),
            vk_physical_device_performance_counters_by_region_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDevicePerformanceCountersByRegionPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PERFORMANCE_COUNTERS_BY_REGION_PROPERTIES_ARM)),
            vk_physical_device_shader_long_vector_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceShaderLongVectorPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_LONG_VECTOR_PROPERTIES_EXT)),
            vk_physical_device_shader_split_barrier_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceShaderSplitBarrierPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SPLIT_BARRIER_PROPERTIES_EXT)),
            vk_physical_device_descriptor_heap_properties_e_x_t: Some(maybe_init!(svk::VkPhysicalDeviceDescriptorHeapPropertiesEXT, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_HEAP_PROPERTIES_EXT)),
            vk_physical_device_descriptor_heap_tensor_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceDescriptorHeapTensorPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_HEAP_TENSOR_PROPERTIES_ARM)),
            vk_physical_device_shader_instrumentation_properties_a_r_m: Some(maybe_init!(svk::VkPhysicalDeviceShaderInstrumentationPropertiesARM, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INSTRUMENTATION_PROPERTIES_ARM)),
            vk_physical_device_shader_abort_properties_k_h_r: Some(maybe_init!(svk::VkPhysicalDeviceShaderAbortPropertiesKHR, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ABORT_PROPERTIES_KHR)),
            vk_physical_device_buffer_device_address_allocation_alignment_properties_v_a_l_v_e: Some(maybe_init!(svk::VkPhysicalDeviceBufferDeviceAddressAllocationAlignmentPropertiesVALVE, svk::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_ALLOCATION_ALIGNMENT_PROPERTIES_VALVE)),

        }
    }

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ///
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    pub fn buildPNext(&mut self) -> *mut std::ffi::c_void {
        let ptr_ = self.vk_physical_device_vulkan_1_1_properties.as_mut().unwrap().as_mut_ptr();
        let ptr_next_ = self.vk_physical_device_vulkan_1_2_properties.as_mut().unwrap().as_mut_ptr();
        
        unsafe {
            (*ptr_).pNext = ptr_next_ as *mut std::ffi::c_void
        }

        ptr_ as *mut std::ffi::c_void
    }
}