# SPDX-License-Identifier: None
# Copyright (c) 2026 None

[package]
name = "utils__parser_xml_4_sdk_vulkan"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "utils__parser_xml_4_sdk_vulkan"
path = "_mods.rs"

[dependencies]